### ISSUE TITLE
Why ios 8.1 minimum ?

### ISSUE THREAD

**Issue by acidfilez** [rad3ks/RSZInAppNotifications#1]
Can it be 7.0 for the old users?

Greetings

**Comment by rad3ks** [comment]
Hi,

It probably can, however I didn't test the container controller on iOS 7 so I didn't want to risk any issues for users. Later today I'll test and push fixes eventually. Thanks for your interest.

Cheers!

**Comment by rad3ks** [comment]
I've updated pod to work with iOS7. New version was set to '1.0.1'.

Good luck :)
